<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-04-09 15:34

from django.db import migrations, models
=======
# Generated by Django 3.0.5 on 2020-04-23 13:22

from django.db import migrations, models
import users.models
>>>>>>> develop


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
=======
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path)),
>>>>>>> develop
            ],
            options={
                'abstract': False,
            },
        ),
    ]
