# Generated by Django 3.0.6 on 2020-05-20 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateField(default=datetime.datetime.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='not_confirmed', max_length=50)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_giver', to=settings.AUTH_USER_MODEL)),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_taker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
